### ISSUE TITLE
Error (The requested accessory 'AutomationBluetoothPresence' was not registered by any plugin)

### ISSUE THREAD

**Issue by monza258** [paolotremadio/homebridge-automation-bluetooth-presence#13]
Hey, 

I have an error that Plugin was not installed.

```
[2020-3-16 7:07:22] Error: The requested accessory 'AutomationBluetoothPresence' was not registered by any plugin.
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:64:13)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:297:42)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:91:38)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:59:10)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Module._compile (internal/modules/cjs/loader.js:1158:30)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Module.load (internal/modules/cjs/loader.js:1002:32)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Function.Module._load (internal/modules/cjs/loader.js:901:14)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
Mär 16 07:07:22 raspberrypi2 homebridge[9056]: [2020-3-16 7:07:22] Got SIGTERM, shutting down Homebridge...
Mär 16 07:07:27 raspberrypi2 systemd[1]: homebridge-people.service: Main process exited, code=exited, status=143/n/a
Mär 16 07:07:27 raspberrypi2 systemd[1]: homebridge-people.service: Unit entered failed state.
Mär 16 07:07:27 raspberrypi2 systemd[1]: homebridge-people.service: Failed with result 'exit-code'.
```

My Config:

```
"accessories" : [
    {
      "accessory" : "AutomationBluetoothPresence",
      "deviceId" : "2c:fc:e4:00:da:8a",
      "gracePeriod" : 300,
      "name" : "CTEK"
    },
    {
      "accessory" : "AutomationBluetoothPresence",
      "deviceId" : "ff:ff:3d:14:80:78",
      "gracePeriod" : 300,
      "name" : "iTag"
    },
    {
      "accessory" : "AutomationBluetoothPresence",
      "deviceId" : "ff:ff:c5:15:f5:f8",
      "gracePeriod" : 300,
      "name" : "iTag2"
    }
  ]
```

**Comment by emptygalaxy** [comment]
May be related to this issue:
The plugin "homebridge-automation-bluetooth-presence" defines 'homebridge' and/or 'hap-nodejs' in their 'dependencies' section, meaning they carry an additional copy of homebridge and hap-nodejs. This not only wastes disk space, but also can cause major incompatibility issues and thus is considered bad practice. Please inform the developer to update their plugin!

**Comment by paolotremadio** [comment]
It works anyway. Don’t worry
