### ISSUE TITLE
Cannot find module 'bluetooth-hci-socket'

### ISSUE THREAD

**Issue by testpaul999** [paolotremadio/homebridge-automation-bluetooth-presence#6]
Hi,
if I let run sudo automation-bt-detect-devices I get this error.

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-automation-bluetooth-presence/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

pi@386pi:~$ node -v
v10.15.3
pi@386pi:~$ npm -v
6.9.0

Thanks for help.

regards

**Comment by testpaul999** [comment]
Run's fine with node 8.x
can close
